version: "3"
services: 
  api:
    build: .
    ports:
      - 8000:8000
    # env-file:
    #   -./.env
    volumes:   #sync the local code to update automatically with the container
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=192.168.1.86
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=fastAPi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fastAPi

    volumes:
      - postgres_db:/var/lib/postgresql/data/

volumes:
  postgres_db:
